### ISSUE TITLE
Chain ID mapping

### ISSUE THREAD

**Issue by hujw77** [darwinia-network/darwinia-msgport#8]
```
chain_id = SDK.getChainId(msg_port_chain_id, dock_addr)
```
Ref: https://chainlist.org

**Comment by jiguantong** [comment]
Where should we maintain the chainId mapping?
If do it in contract dock, every time a chainId is added, each dock needs to be upgraded.
If do it offchain, how to ensure that users are not aware of chainId changes? How to ensure that the `recv` interface receives msgport chainId rather than other chainId?

**Comment by jiguantong** [comment]
If do it in contract dock, every time a chainId is added, each chain-id-mapping contract needs to be upgraded or update
